# 04/06/2020

### Numpy package:
1. Numerical data
2. Computations on numerics

In [1]:
import numpy as np


### Difference Betwwen numpy array and List:
1. Less memory
2. fast
3. Convenient

In [8]:
# 1-dimenstional array
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [12]:
# 2-dimensional array
a1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1.ndim

2

In [6]:
a1.shape

(3, 3)

In [7]:
a.shape

(5,)

In [11]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])#rows
print(a2.shape[1])#columns

4
3


In [16]:
a3=np.array([],dtype="int32")

In [18]:
a3 = np.append(a3,int(input()))
a3

12


array([12, 12])

In [19]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([12, 12, 23, 34, 45, 56, 67])

In [20]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Slicing:

In [21]:
print(a3[3])

34


In [22]:
a3

array([12, 12, 23, 34, 45, 56, 67])

In [23]:
print(a2[1,1])

5


In [24]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [25]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [26]:
print(a2[0,0:2])

[1 2]


In [29]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


### Iterate through array:

In [32]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [33]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [34]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### indexing with boolean array

In [36]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [41]:
result= (arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [42]:
arr1[result]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending Array

In [50]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))#Vertical stcaking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [51]:
print(np.hstack((arr1,arr2)))#horizonatal stcking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. iteamsize
3. dtype
4. ndim
5. shape

In [54]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. Linspace()
6. arange()
7. reshape()
8. ravel()

In [62]:
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [64]:
o=np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
f=np.full((2,2),"Vardhan")
print(f)

[['Vardhan' 'Vardhan']
 ['Vardhan' 'Vardhan']]


In [69]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
#Linspace()-->Linear spacing elements
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [73]:
a= np.arange(1,11,2) #range(start,stop,step)
a

array([1, 3, 5, 7, 9])

In [77]:
#ravel()--->flattens your array elements
print(np.array(a.flat))
print(a.ravel())

[1 3 5 7 9]
[1 3 5 7 9]


### Function:
1. min()
2. max()
3. sum()
4. sqrt()
5. std()
6. mean()
7. median()


In [78]:
print(a.min())
print(a.max())

1
9


In [79]:
a

array([1, 3, 5, 7, 9])

In [81]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

25


AxisError: axis 1 is out of bounds for array of dimension 1

In [82]:
np.sqrt(a)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ])

In [83]:
np.mean(a)

5.0

In [84]:
np.median(a)

5.0

In [86]:
np.std(a) #standard deviation

2.8284271247461903

### Mathematical Opeartions:+,-,*,/,%


In [89]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)


[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


### dot()-->Matrix multiplication
### arr1 = m X n
### arr2 = nX I


In [91]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [92]:
#transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [93]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Applying user-defined function:


In [94]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [98]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [96]:
# 1/(1+1)-->x/(x=1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [101]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])