# 05/06/2020

# Numpy random packages

In [10]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

7
0.583882802400038


In [11]:
# Creating n-dimentional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[23 25 26]
[[30 83 48 39]
 [49  7 17 24]
 [77 85 89 35]]
[[[46 93]
  [10 80]
  [44 27]
  [91  1]]

 [[54 58]
  [45 18]
  [38 55]
  [83 72]]

 [[98 36]
  [68 25]
  [98 66]
  [ 2 28]]]


In [12]:
# Creating n-dimentional array with random floating values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.8862108521608133
[0.44072994 0.18816642 0.7366286 ]
[[0.65575819 0.59908556 0.4862242 ]
 [0.66593938 0.39362229 0.32372975]]


In [13]:
a=random.randint(100,size=(3,2)).ravel()
a

array([15, 55, 14, 15, 40, 70])

In [14]:
#Single element will be selected
random.choice(a)

14

In [15]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(5,5))

array([[2, 2, 4, 2, 3],
       [4, 4, 1, 5, 1],
       [2, 1, 2, 5, 2],
       [3, 5, 1, 1, 3],
       [5, 5, 1, 2, 2]])

# Pandas
1. Data maniplation, Analysis and cleaning
2. Tabular, Unlabelled

### Creating a dataframe
1. Using 2 dictionaries
2. Simple dictionary -->DataFrame


In [16]:
#  Using 2 dictionaries
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [17]:
#Simple dictionary -->DataFrame
d1={"name":["vardhan","reddy","ajay"],"address":["hyd","adb","Ap"]}
df1=pd.DataFrame(d1)
df1

name address
0  vardhan     hyd
1    reddy     adb
2     ajay      Ap

In [21]:
# 3.Using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.5,67.4,67.78,34.45,23.34,27.4,23.34,67.23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.50       c
3        4    67.40       d
4        5    67.78       e
5        6    34.45       f
6        7    23.34       g
7        8    27.40       h
8        9    23.34       i
9       10    67.23       j

### Selecting the data from the DataFrame:
1. loc
2. iloc

In [24]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.50       c
3    67.40       d
4    67.78       e
5    34.45       f
6    23.34       g
7    27.40       h
8    23.34       i
9    67.23       j

In [27]:
#Single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [34]:
# Extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.50
3        4    67.40
4        5    67.78
5        6    34.45

In [35]:
type(df3)

pandas.core.frame.DataFrame

In [36]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [39]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [41]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [42]:
df3.shape

(10, 3)

In [44]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [45]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [47]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.50       c
3        4    67.40       d
4        5    67.78       e

In [50]:
# Last five rows
df3.tail()

column1  column2 column3
5        6    34.45       f
6        7    23.34       g
7        8    27.40       h
8        9    23.34       i
9       10    67.23       j

In [52]:
# Print randomly
df3.sample()

column1  column2 column3
4        5    67.78       e

In [53]:
df3.sample(3)

column1  column2 column3
0        1    12.23       a
6        7    23.34       g
2        3    45.50       c

In [56]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  39.201000
std     3.02765  21.294834
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  30.925000
75%     7.75000  61.797500
max    10.00000  67.780000

### Change the Column Headers and index


In [60]:
# Renaming the column headers
df3=df3.rename(columns={"column1":"First",
                    "column2":"Second",
                    "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.50     c
3      4   67.40     d
4      5   67.78     e
5      6   34.45     f
6      7   23.34     g
7      8   27.40     h
8      9   23.34     i
9     10   67.23     j

In [61]:
arr1 = np.arange(9).reshape(3,3)

arr1[:,[1,2]] = arr1[:,[2,1]]

print(arr1)

[[0 2 1]
 [3 5 4]
 [6 8 7]]
